const { cmd } = require("../command");
const axios = require("axios");
const fs = require("fs");
const path = require("path");

cmd({
    pattern: "img",
    alias: ["quzimg", "genimg", "teaimg", "txt2img"],
    react: "🎨",
    desc: "Generate AI images from text (Free via Quizontal)",
    category: "ai",
    filename: __filename,
},
async (bot, mek, m, { from, q, reply }) => {
    try {
        if (!q) {
            return reply("🎨 *Please describe your image*\n\nExample: .aimg a beautiful sunset over mountains, digital art");
        }

        await bot.sendMessage(from, {
            text: `🎨 *Generating AI Image...*\n\n📝 *Prompt:* ${q}\n⏳ Please wait 20-30 seconds`
        }, { quoted: mek });

        // Quizontal API endpoint - Note: You may need to check their actual API endpoint
        const apiUrl = "https://www.quizontal.online/api/ai-image-generator";
        
        try {
            const response = await axios.post(apiUrl, {
                prompt: q,
                style: "digital-art", // Default style
                resolution: "1024x1024"
            }, {
                headers: {
                    'Content-Type': 'application/json',
                    'Origin': 'https://www.quizontal.online',
                    'Referer': 'https://www.quizontal.online/ai-tools/ai-image-generator'
                },
                timeout: 30000 // 30 second timeout
            });

            if (response.data && response.data.image_url) {
                // Download the generated image
                const imageUrl = response.data.image_url;
                const imagePath = path.join(__dirname, `${Date.now()}_ai.jpg`);
                
                const imageRes = await axios({
                    url: imageUrl,
                    method: 'GET',
                    responseType: 'stream'
                });
                
                const writer = fs.createWriteStream(imagePath);
                imageRes.data.pipe(writer);
                
                await new Promise((resolve, reject) => {
                    writer.on('finish', resolve);
                    writer.on('error', reject);
                });

                // Send the image
                await bot.sendMessage(from, {
                    image: fs.readFileSync(imagePath),
                    caption: `🎨 *AI Image Generated*\n\n📝 *Prompt:* ${q}\n\n🆓 Generated by Quizontal AI - 100% Free\n\n> MALIYA-MD ❤️`
                }, { quoted: mek });

                // Clean up
                fs.unlinkSync(imagePath);
            } else {
                // Alternative: Use their web interface approach
                const webUrl = `https://www.quizontal.online/ai-tools/ai-image-generator?prompt=${encodeURIComponent(q)}`;
                await bot.sendMessage(from, {
                    text: `🎨 *AI Image Generator*\n\n⚠️ Direct API not available.\n\n🔗 *Click here to generate:*\n${webUrl}\n\n👉 Generate image and send here.`,
                    detectLink: true
                }, { quoted: mek });
            }
            
        } catch (apiError) {
            console.log("API Error:", apiError);
            
            // Fallback: Send website link
            const webUrl = `https://www.quizontal.online/ai-tools/ai-image-generator?prompt=${encodeURIComponent(q)}`;
            await bot.sendMessage(from, {
                text: `🎨 *Quizontal AI Image Generator*\n\n📝 *Prompt:* ${q}\n\n🔗 *Generate image here:*\n${webUrl}\n\n👉 Click link → Paste prompt → Download image → Send here\n\n✅ 100% Free, No Watermarks`,
                detectLink: true
            }, { quoted: mek });
        }
        
    } catch (e) {
        console.log("AI Image Error:", e);
        reply("❌ Error generating image. Please try again later.");
    }
});
